// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('izefjnz', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('izefjnz', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 716, height: 672 })
    await driver.findElement(By.css("input:nth-child(1)")).click()
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys("ines")
    await driver.findElement(By.css("input:nth-child(2)")).click()
    assert(await driver.switchTo().alert().getText() == "Success")
  })
})
